version: '3.4'

services:
  mongo:
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
        MONGO_INITDB_DATABASE: Books
    networks:
      - booklist-network

  booklist-api:
    container_name: booklist-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "BookListDatabase:ConnectionString=mongodb://mongo:27017"
    depends_on:
      - mongo
    ports:
      - "8000:80"
    networks:
      - booklist-network
